baseURL: "https://bhat-meghana.github.io/" 
title: Meghana Bhat
pagination:
  pagerSize: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Home
          url: /
          weight: 1
        - name: Research
          url: research/
          weight: 2
        - name: Education
          url: education/
          weight: 3 
        - name: Teaching
          url: teaching/
          weight: 4
        - name: Visits
          url: visits/
          weight: 5  
        - name: Miscellaneous
          url: miscellaneous/
          weight: 6
          children:  # This defines the sub-pages under Miscellaneous
            - name: Links
              url: miscellaneous/links/  # You can adjust the URL as needed
              weight: 1
            - name: Photo Album
              url: miscellaneous/musings/  # You can adjust the URL as needed
              weight: 2

params:
    description: "I'm a PhD student in Mathematics at the Indian Institute of Technology Dharwad.
                  My research interest is in Commutative algebra. In particular, 
                  I work on problems related to Hilbert functions."
    author: "Meghana Bhat"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Meghana Bhat
          subtitle: "I am a Research Fellow(PostDoc) hosted by <a href='https://sites.google.com/view/pduttashomepage' style='color: navy;'>Prof. Pranjal Dutta</a> in the College of Computing and Data Science(CCDS) at the Nanyang Technological University(NTU), Singapore. 
                    <br>
                     My research interest is in <i style='color: navy;'>Commutative algebra and Algebraic Geometry</i> and its applications to other fields like <i style='color: navy;'>Algebraic Complexity Theory</i>. In particular, I have worked on problems related to <i style='color: navy;'>Hilbert functions</i>, and <i style='color: navy;'>Waring rank of forms</i>.
                    <br>
                    <br>
                    I received my PhD in Mathematics from <a href='https://www.iitdh.ac.in' style='color: navy;'>Indian Institute of Technology Dharwad</a> in July 2026. 
                    My Ph.D. thesis advisor was <a href='https://www.iitdh.ac.in/user-profile/shreedevi-masuti' style='color: navy;'>Prof. Shreedevi Masuti</a>. 
                    I was also a SPARC visiting research student at the Politecnico Di Torino, Italy, under the mentorship of <a href='https://www.polito.it/personale?p=enrico.carlini' style='color: navy;'>Prof. Enrico Carlini</a>.
                    During my Ph.D., I was a <a href='/PMRFCerti.pdf' target='_blank' rel='noopener noreferrer' style='color: navy;'>Prime Minister's Research Fellow</a>. Funding from PMRF has been instrumental in my research journey.
                    <br>
                    <br>
                    Contact: mbhat.math@gmail.com, meghana.bhat@ntu.edu.sg
                    <br>"
          imageUrl: "profile_picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Meghana Bhat
          buttons:
            - name: Research
              url: research/
            - name: Education
              url: education/ 
            - name: Teaching
              url: teaching/
            - name: Visits
              url: visits/   
            - name: Miscellaneous
              url: miscellaneous/
    socialIcons:
        - name: CV
          url: /20260325.pdf
        - name: Email
          url: mailto:mbhat.math@gmail.com
        - name: LinkedIn
          url: https://www.linkedin.com/in/meghanamath

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Meghana Bhat"
      icon: faviconM.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
